services:
  apache:
    build: .
    ports:
      - "${APACHE_PORT}:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/apache2/sites-enabled:/etc/apache2/sites-enabled
      - /etc/apache2/sites-available:/etc/apache2/sites-available
    env_file:
      - ".env"
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    expose:
      - "${DB_PORT}"
    env_file:
      - ".env"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: game1to1
  websock:
    build:
      context: .
      dockerfile: Dockerfile_websock
    ports:
      - "${WEBSOCK_PORT}:9000"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - ".env"
